services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_ENVIRONMENT: docker
      APP_DATABASE_URL: postgresql://portfolio:portfolio@postgres:5432/portfolio
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: portfolio
      POSTGRES_PASSWORD: portfolio
    ports:
      - "5432:5432"
